apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed

spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: kamariza/udagram-api-feed
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: udagram-secrets
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true  
        imagePullPolicy: Always          

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"         
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret   

---
# Service part
apiVersion: v1
kind: Service
metadata:
  name: feed-api
spec:
  selector:
    app: udagram-api-feed
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  