apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-users
  name: udagram-api-users-svc
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    service: udagram-api-users
