apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-users

spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-users
  template:
    metadata:
      labels:
        app: udagram-api-users
    spec:
      containers:
      - image: kamariza/udagram-api-users
        name: udagram-api-users
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: udagram-secrets
      restartPolicy: Always

---
# Service part
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  selector:
    app: udagram-api-users
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  