apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - name: "8110"
    port: 8110
    targetPort: 8110
  selector:
    service: udagram-frontend
